/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import controller.StudentController;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dolch
 */
public class Student extends javax.swing.JFrame {

    /**
     * Creates new form Student
     */
    public Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_studentdata = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        add_student = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_studentdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "StudentId", "FirstName", "MiddleName", "LastName", "Email", "reg_no", "address", "gender", "blood_group", "dob", "academic_background"
            }
        ));
        jScrollPane1.setViewportView(tbl_studentdata);

        jButton1.setText("ViewStudent");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_edit.setText("EditStudent");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jButton3.setText("DeleteStudent");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        add_student.setText("AddStudent");
        add_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_studentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_student, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(32, 32, 32)
                .addComponent(btn_edit)
                .addGap(50, 50, 50)
                .addComponent(jButton3)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btn_edit)
                    .addComponent(jButton3)
                    .addComponent(add_student))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          StudentController sc = new StudentController();
        try {
            ResultSet rs = sc.getStudentList();
            ResultSetMetaData meta = (ResultSetMetaData) rs.getMetaData();
            
            DefaultTableModel model = (DefaultTableModel)tbl_studentdata.getModel();
            
            int cols = meta.getColumnCount();
            String[] colName = new String[cols];
            
            for(int i =0; i<cols; i++){
                colName[i] = meta.getColumnName(i + 1);
                model.setColumnIdentifiers(colName);
            }
            String id, first_name,middle_name, last_name,email,user_id, reg_no, address,gender,blood_group,dob,academic_backgroud;
            while(rs.next()){
                id = rs.getInt("student_id") + "";
                first_name = rs.getString("first_name");
                middle_name = rs.getString("middle_name");
                last_name = rs.getString("last_name");
                email = rs.getString("email");
                user_id = rs.getString("user_id");
                reg_no = rs.getString("reg_no");
                address = rs.getString("address");
                gender = rs.getString("gender");
                blood_group = rs.getString("blood_group");
                dob = rs.getString("dob");
                academic_backgroud = rs.getString("academic_background");
                
                String[] row = {id, first_name,middle_name,last_name, email,user_id,  reg_no, address, gender, blood_group, dob,academic_backgroud};
                model.addRow(row);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) tbl_studentdata.getModel();
        int row = tbl_studentdata.getSelectedRow();
        
        String id = (String) model.getValueAt(row, 0);
        String first_name = (String) model.getValueAt(row , 1);
        String middle_name = (String) model.getValueAt(row, 2);
        String last_name = (String) model.getValueAt(row, 3);
        String email = (String) model.getValueAt(row, 4);
        String user_id = (String) model.getValueAt(row, 5);
        String reg_no = (String) model.getValueAt(row, 6);
        String address = (String) model.getValueAt(row, 7);
        String gender = (String) model.getValueAt(row, 8);
        String blood_group = (String) model.getValueAt(row, 9);
        String dob = (String) model.getValueAt(row, 10);
        String academic_backgroud = (String) model.getValueAt(row, 11);


        
        StudentEdit se = new StudentEdit();
        se.setStudentFormData(id, first_name, middle_name, last_name, email, user_id,reg_no,address, gender, blood_group, dob, academic_backgroud);
        se.setVisible(true);
    }//GEN-LAST:event_btn_editActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tbl_studentdata.getModel();
        int row = tbl_studentdata.getSelectedRow();
        String student_id = (String) model.getValueAt(row, 0);
        DeleteStudent ds = new DeleteStudent();
        ds.setStudentFormData(student_id);
        ds.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void add_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_studentActionPerformed
        // TODO add your handling code here:
        StudentRegistrationForm srf = new StudentRegistrationForm();
        this.dispose();
        srf.setVisible(true);
    }//GEN-LAST:event_add_studentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_student;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_studentdata;
    // End of variables declaration//GEN-END:variables
}
